Pin marshmallow <= 2.21
marshmallow > 3 with FAB

```
ERROR: flask-appbuilder 2.3.2 has requirement marshmallow<3.0.0,>=2.18.0, but you'll have marshmallow 3.9.1 which is incompatible.
```

(cherry picked from commit 17e52868200522015ae20987b76b7ff1a60c8840)